blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.PostIndex.as_view(), name='index'),
    path('categoria/<str:categoria>', views.PostCategoria.as_view(), name='post_categoria'),
    path('busca/', views.PostBusca.as_view(), name='post_busca'),
    path('post/<int:pk>', views.PostDetalhes.as_view(), name='post_detalhes'),
]

categorias/models.py
from django.db import models

class Categoria(models.Model):
    nome_cat = models.CharField(max_length=50, verbose_name='Nome')

    def __str__(self) -> str:
        return self.nome_cat

comentarios/models.py
from django.db import models
from posts.models import Post
from django.contrib.auth.models import User
from django.utils import timezone

class Comentario(models.Model):
    nome_comentario = models.CharField(max_length=255, verbose_name='Autor')
    email_comentario = models.EmailField(max_length=255, verbose_name='Email')
    comentario = models.TextField(verbose_name='Comentário')
    post_comentario = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Post')
    usuario_comentario = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name='Usuário', blank=True, null=True)
    data_comentario = models.DateTimeField(default=timezone.now, verbose_name='Data')
    publicado_comentario = models.BooleanField(default=False, verbose_name='Está público?')

    def __str__(self) -> str:
        return self.nome_comentario

posts/models.py
from django.db import models
from categorias.models import Categoria
from django.contrib.auth.models import User
from django.utils import timezone


class Post(models.Model):
    titulo_post = models.CharField(max_length=255, verbose_name='Título')
    autor_post = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name='Autor')
    data_post = models.DateTimeField(default=timezone.now, verbose_name='Data')
    conteudo_post = models.TextField(verbose_name='Conteúdo')
    excerto_post = models.TextField(verbose_name='Excerto')
    categoria_post = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING, blank=True, null=True, verbose_name='Categoria')
    imagem_post = models.ImageField(upload_to='post_img/%Y/%m/%d', blank=True, null=True, verbose_name='Imagem')
    publicado_post = models.BooleanField(default=False, verbose_name='Está público?')

    def __str__(self) -> str:
        return self.titulo_post

comentarios/forms.py
from django.forms import ModelForm
from .models import Comentario

class FormComentario(ModelForm):
    def clean(self):
        data = self.cleaned_data
        nome = data.get('nome_comentario')
        email = data.get('email_comentario')
        comentario = data.get('comentario')

      
    class Meta:
        model = Comentario
        fields = ('nome_comentario', 'email_comentario', 'comentario')

categorias/views.py
from django.shortcuts import render

# Create your views here.

comentarios/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from typing import List
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from .models import Post
from django.db.models import Q, Count, Case, When
from categorias.models import Categoria
from comentarios.forms import FormComentario
from comentarios.models import Comentario
from django.contrib import messages

class PostIndex(ListView):
    model = Post
    template_name = 'posts/index.html'
    paginate_by = 3
    context_object_name = 'posts'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.order_by('-id').filter(publicado_post=True)
        qs = qs.annotate(
            numero_comentarios=Count(
                Case(
                    When(comentario__publicado_comentario=True, then=1)
                )
            )
        )
        return qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorias'] = Categoria.objects.all()
        return context

class PostBusca(PostIndex):
    template_name = 'posts/post_busca.html'
    
    def get_queryset(self):
        qs = super().get_queryset()
        termo = self.request.GET.get('termo')
        if not termo:
            return qs
        qs = qs.filter(
            Q(titulo_post__icontains=termo) |
            Q(autor_post__first_name__iexact=termo) |
            Q(conteudo_post__icontains=termo) |
            Q(excerto_post__icontains=termo) |
            Q(categoria_post__nome_cat__iexact=termo) 
        )
        
        return qs

class PostCategoria(PostIndex):
    template_name = 'posts/post_categoria.html'
    def get_queryset(self):
        qs = super().get_queryset()

        categoria = self.kwargs.get('categoria', None)
        if not categoria:
            return qs
            
        qs = qs.filter(categoria_post__nome_cat__iexact=categoria)
        return qs

class PostDetalhes(UpdateView):
    template_name = 'posts/post_detalhes.html'
    model = Post
    form_class = FormComentario
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        post = self.get_object()
        comentarios = Comentario.objects.filter(publicado_comentario=True, post_comentario=post.id)
        contexto['comentarios'] = comentarios
        contexto['categorias'] = Categoria.objects.all()
        return contexto

    def form_valid(self, form):
        post = self.get_object()
        comentario  = Comentario(**form.cleaned_data)
        comentario.post_comentario = post
        
        if self.request.user.is_authenticated:
            comentario.usuario_comentario = self.request.user
        
        comentario.save()
        messages.success(self.request, 'Comentário enviado para revisão')
        return redirect('post_detalhes', pk=post.id)

posts/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block 'conteudo' %}
<div class="card-columns mt-4">
    
    {% for post in posts %}
        <div class="card">
            {% if post.imagem_post %}
            <a href="{% url 'post_detalhes' post.id %}">
                <img class="card-img-top" src="{{ post.imagem_post.url }}" 
                alt="{{ post.titulo_post }}">
            </a>
            {% else %}
            <a href="{% url 'post_detalhes' post.id %}">
                <img class="card-img-top" src="{% static 'defaultPost.jpg' %}" 
                alt="{{ post.titulo_post }}">
            </a>
            {% endif %}

            <div class="card-body">
                <h5 class="card-title">
                    <a href="{% url 'post_detalhes' post.id %}">
                        {{ post.titulo_post }}
                    </a>
                </h5>
                <p class="card-text">{{ post.excerto_post }}</p>
                <p class="card-text">
                    <small class="text-muted">
                        {{ post.data_post|naturalday|title }} | 
                        {{ post.comentario_set.count }} comentário(s) | 
                        {{ post.categoria_post }}
                        </small>
                </p>

                <div class="text-right">
                    <a href="{% url 'post_detalhes' post.id %}" class="btn btn-outline-secondary">Ler mais...</a>
                </div>
            </div>
        </div>
    {% endfor %}
    
</div>
    {% include 'partials/_pagination.html' %}
{% endblock %}

posts/templates/posts/post_busca.html
{% extends 'posts/index.html' %}
{% block 'titulo' %} {{ request.GET.termo|title }} | Pesquisa | {% endblock %}

posts/templates/posts/post_categoria.html
{% extends 'posts/index.html' %}
{% block 'titulo' %} {{ view.kwargs.categoria|title }} | Categoria | {% endblock %}

posts/templates/posts/post_detalhes.html
{% extends 'base.html' %}
{% block 'titulo' %} {{ post.titulo_post|title }} | {% endblock %}

{% block 'conteudo' %}
<div class="container">
    <div class="row pt-5">
        <div class="col-xl"></div>
        <div class="col-xl-8 text-center">
            <h2>{{ post.titulo_post }}</h2>
            <h5>{{ post.excerto_post }}</h5>
            <p class="text-muted mt-4">
                <small>
                    {{ post.autor_post }} | {{ post.data_post }} | {{ post.categoria_post }}
                </small>
            </p>
        </div>
        <div class="col-xl"></div>
    </div>

    <div class="row pt-5">
        <div class="col-xl"></div>
        <div class="col-xl-8">
            {% if post.imagem_post %}
            <img class="img-fluid pb-5 " src="{{ post.imagem_post.url }}" alt="{{ post.titulo_post }}">
            {% endif %}

            {{ post.conteudo_post|safe }}
            
        </div>
        <div class="col-xl"></div>
    </div>

    {% if comentarios %}
        <div class="row pt-5">
            <div class="col-xl"></div>
            <div class="col-xl-8">
            <h2 class="my-3">Comentários ({{ comentarios.count }})</h2>

            {% for comentario in comentarios %}    

                <h5 class="mb-2 mt-5">{{ comentario.nome_comentario }} disse:</h5>
                <small class="text-muted">{{ comentario.data_comentario }}</small>
                <p class="mb-1">{{ comentario.comentario }}</p>      
            
            {% endfor %}


                
            </div>
            <div class="col-xl"></div>
        </div>
        {% endif %}
        
        
        <div class="row pt-5">
            <div class="col-xl"></div>
            <div class="col-xl-8">
                <h2 class="my-3">Deixe um comentário</h2>

            <form method="POST" action="#envia_comentario">
                {% csrf_token %}
                <table class="table">
                    {{ form }}
                    <tr>
                        <td colspan="2">
                            {% include 'partials/_messages.html' %}
                            <input id="envia_comentario" type="submit" class="btn btn-primary" value="Comentar">
                        </td>
                    </tr>
                </table>
            </form>
        </div>
        <div class="col-xl"></div>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt">

<head>
    <title>{% block 'titulo' %}{% endblock %}Blog</title>
    {% include 'partials/_head.html' %}
</head>

<body>
{% include 'partials/_nav.html' %}

<!-- Page Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-12">

            <!-- CONTENT -->
            {% block 'conteudo' %}
            {% endblock %}
            <!--/CONTENT-->


           

        </div>
    </div>
</div>

{% include 'partials/_footer.html' %}

</body>

</html>

templates/partials/_footer.html
{% load static %}
<footer class="bg-primary text-light static-bottom">
    <div class="container navbar-dark pt-4 mt-5">
        
        <div class="row">
            <div class="col">
                <p class="text-left">Meu blog</p>
            </div>
            <div class="col">
                {% for categoria in categorias %}
                    <a class="text-white" href="{% url 'post_categoria' categoria %}"><p class="text-right">{{ categoria }}</p></a>
                {% endfor %}
            </div>
        </div>
                        
                
    </div>
</footer>
<!--/_footer.html-->

<script src="{% static 'vendor/jquery/jquery.slim.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

templates/partials/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'vendor/bootstrap/css/theme_1564087106285.css' %}" rel="stylesheet">

templates/partials/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/partials/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary static-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% for categoria in categorias %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'post_categoria' categoria %}">
                            {{ categoria }}
                        </a>
                    </li>
                 {% endfor %}

            </ul>
            <form class="form-inline my-2 my-lg-0 ml-lg-4" action="{% url 'post_busca' %}">
                <input name="termo" value="{{ request.GET.termo }}" class="form-control mr-sm-2" type="search" placeholder="Pesquisar"
                       aria-label="Search">
            </form>
        </div>
    </div>
</nav>

templates/partials/_pagination.html
{% if is_paginated %}
<div class="pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}
        <li class="page-item active">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endif %}